language: scala
jdk: openjdk11
os: linux
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - name: checks
      scala: 2.12.10
      script: sbt scalafmtCheckAll scalafmtSbtCheck

    - scala: 2.12.10
      env: PLATFORM="jvm"
      script: sbt "++ ${TRAVIS_SCALA_VERSION}" coverage jvm/checkCI docs/tut coverageReport && codecov

    - scala: 2.12.10
      env: PLATFORM="js"
      script: sbt "++ ${TRAVIS_SCALA_VERSION}" js/checkCI

    - scala: 2.13.1
      env: PLATFORM="jvm"
      script: sbt "++ ${TRAVIS_SCALA_VERSION}" jvm/checkCI

    - scala: 2.13.1
      env: PLATFORM="js"
      script: sbt "++ ${TRAVIS_SCALA_VERSION}" js/checkCI

    - scala: 3.0.0-M1
      env: PLATFORM="jvm"
      script: sbt "++ ${TRAVIS_SCALA_VERSION}" jvm/checkCI

    - scala: 3.0.0-M1
      env: PLATFORM="js"
      script: sbt "++ ${TRAVIS_SCALA_VERSION}" js/checkCI

    - stage: release
      script: sbt ci-release

install:
  - pip install --user codecov

cache:
  directories:
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
